"""Shared utilities for managing target companies and detecting job board connectors.

Used by both the setup wizard (setup.py) and the add-target CLI command (cli.py).
"""

from __future__ import annotations

import re
from pathlib import Path

import httpx
import yaml

CONFIG_DIR = Path(__file__).resolve().parents[3] / "config"
TARGETS_PATH = CONFIG_DIR / "targets.yml"

TARGETS_HEADER = """\
# MyScout Target Companies — generated by `python -m myscout setup`
# Edit freely. See config/targets.yml.example for slug-finding tips.
#
# To test a slug:
#   curl -s "https://api.lever.co/v0/postings/SLUG?mode=json" | head -c 100
#   curl -s "https://boards-api.greenhouse.io/v1/boards/SLUG/jobs" | head -c 100

"""


def slugify(name: str) -> str:
    """Convert a company name to a URL slug."""
    s = name.lower().strip()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s]+", "-", s)
    return s


def detect_connectors(slug: str) -> list[tuple[str, int]]:
    """Probe Lever, Greenhouse, and Ashby APIs to detect available connectors.

    Returns a list of (connector_type, job_count) tuples for each board that
    has jobs for the given slug.
    """
    results = []
    # Lever
    try:
        r = httpx.get(
            f"https://api.lever.co/v0/postings/{slug}?mode=json",
            timeout=10, follow_redirects=True,
        )
        if r.status_code == 200:
            data = r.json()
            if isinstance(data, list) and len(data) > 0:
                results.append(("lever", len(data)))
    except (httpx.HTTPError, ValueError):
        pass

    # Greenhouse
    try:
        r = httpx.get(
            f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs",
            timeout=10, follow_redirects=True,
        )
        if r.status_code == 200:
            data = r.json()
            if "jobs" in data and len(data["jobs"]) > 0:
                results.append(("greenhouse", len(data["jobs"])))
    except (httpx.HTTPError, ValueError):
        pass

    # Ashby
    try:
        r = httpx.get(
            f"https://api.ashbyhq.com/posting-api/job-board/{slug}",
            timeout=10, follow_redirects=True,
        )
        if r.status_code == 200:
            data = r.json()
            if "jobs" in data and len(data["jobs"]) > 0:
                results.append(("ashby", len(data["jobs"])))
    except (httpx.HTTPError, ValueError):
        pass

    return results


def load_targets() -> dict:
    """Load existing targets.yml, returning an empty structure if missing."""
    if TARGETS_PATH.exists():
        with open(TARGETS_PATH) as f:
            data = yaml.safe_load(f) or {}
    else:
        data = {}
    if "targets" not in data:
        data["targets"] = []
    return data


def save_targets(data: dict) -> None:
    """Write targets dict to targets.yml with the standard header."""
    body = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    TARGETS_PATH.write_text(TARGETS_HEADER + body, encoding="utf-8")
